In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [8]:
df = pd.read_csv(r"C:\Users\USER\Desktop\Admission_Predict.csv")

In [9]:
df.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Serial No.         400 non-null    int64
 1   GRE Score          400 non-null    int64
 2   TOEFL Score        400 non-null    int64
 3   University Rating  400 non-null    int64
 4   SOP                400 non-null    float64
 5   LOR                400 non-null    float64
 6   CGPA               400 non-null    float64
 7   Research           400 non-null    int64
 8   Chance of Admit    400 non-null    float64
dtypes: float64(4), int64(5)
memory usage: 28.2 KB

In [11]:
df.describe()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000,400.000000
mean,200.500000,316.807500,107.410000,3.087500,3.400000,3.452500,8.598925,0.547500,0.724350
std,115.614301,11.473646,6.069514,1.143728,1.006869,0.898478,0.596317,0.498362,0.142609
min,1.000000,290.000000,92.000000,1.000000,1.000000,1.000000,6.800000,0.000000,0.340000
25%,100.750000,308.000000,103.000000,2.000000,2.500000,3.000000,8.170000,0.000000,0.640000
50%,200.500000,317.000000,107.000000,3.000000,3.500000,3.500000,8.610000,1.000000,0.730000
75%,300.250000,325.000000,112.000000,4.000000,4.000000,4.000000,9.062500,1.000000,0.830000
max,400.000000,340.000000,120.000000,5.000000,5.000000,5.000000,9.920000,1.000000,0.970000

In [12]:
df.isnull().sum()

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [13]:
df.value_counts()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research  Chance of Admit
1           337        118          4                  4.5  4.5   9.65  1         0.92                1
264         324        111          3                  2.5  1.5   8.79  1         0.70                1
274         312        99           1                  1.0  1.5   8.01  1         0.52                1
273         294        95           1                  1.5  1.5   7.64  0         0.49                1
272         299        96           2                  1.5  2.0   7.86  0         0.54                1
                                                                                                     ..
131         339        114          5                  4.0  4.5   9.76  1         0.96                1
130         333        118          5                  5.0  5.0   9.35  1         0.92                1
129         326        112          3                  3.5  3.0   9.10  1         0.84                1
128         319        112          3                  2.5  2.0   8.71  1         0.78                1
400         333        117          4                  5.0  4.0   9.66  1         0.95                1
Length: 400, dtype: int64

In [14]:
df.shape

(400, 9)

In [15]:
df.duplicated().sum()

0

In [17]:
df.drop(columns=["Serial No."],inplace=True)

In [25]:
df.head(2)

,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,337,118,4,4.5,4.5,9.65,1,0.92
1,324,107,4,4.0,4.5,8.87,1,0.76

In [23]:
X = df.iloc[:,0:-1]
Y = df.iloc[:,-1]

In [30]:
X

     GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
0          337          118                  4  4.5   4.5  9.65         1
1          324          107                  4  4.0   4.5  8.87         1
2          316          104                  3  3.0   3.5  8.00         1
3          322          110                  3  3.5   2.5  8.67         1
4          314          103                  2  2.0   3.0  8.21         0
..         ...          ...                ...  ...   ...   ...       ...
395        324          110                  3  3.5   3.5  9.04         1
396        325          107                  3  3.0   3.5  9.11         1
397        330          116                  4  5.0   4.5  9.45         1
398        312          103                  3  3.5   4.0  8.78         0
399        333          117                  4  5.0   4.0  9.66         1

[400 rows x 7 columns]

In [31]:
Y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ...
395    0.82
396    0.84
397    0.91
398    0.67
399    0.95
Name: Chance of Admit , Length: 400, dtype: float64

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.33,random_state=42)

In [34]:
X_train

     GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  Research
258        326          102                  4  5.0   5.0  8.76         1
177        319          110                  3  3.5   3.5  9.04         0
119        327          104                  5  3.0   3.5  8.84         1
194        316          109                  3  3.5   3.0  8.76         0
229        324          111                  4  3.0   3.0  9.01         1
..         ...          ...                ...  ...   ...   ...       ...
71         336          112                  5  5.0   5.0  9.76         1
106        329          111                  4  4.5   4.5  9.18         1
270        306          105                  2  2.5   3.0  8.22         1
348        302           99                  1  2.0   2.0  7.25         0
102        314          106                  2  4.0   3.5  8.25         0

[268 rows x 7 columns]

In [35]:
Y_train

258    0.77
177    0.82
119    0.71
194    0.77
229    0.82
       ...
71     0.96
106    0.87
270    0.72
348    0.57
102    0.62
Name: Chance of Admit , Length: 268, dtype: float64

In [36]:
from sklearn.preprocessing import MinMaxScaler

In [37]:
scaler = MinMaxScaler()

In [38]:
X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [40]:
X_train_trf

array([[0.72      , 0.35714286, 0.75      , ..., 1.        , 0.62820513,
        1.        ],
       [0.58      , 0.64285714, 0.5       , ..., 0.57142857, 0.71794872,
        0.        ],
       [0.74      , 0.42857143, 1.        , ..., 0.57142857, 0.65384615,
        1.        ],
       ...,
       [0.32      , 0.46428571, 0.25      , ..., 0.42857143, 0.45512821,
        1.        ],
       [0.24      , 0.25      , 0.        , ..., 0.14285714, 0.14423077,
        0.        ],
       [0.48      , 0.5       , 0.25      , ..., 0.57142857, 0.46474359,
        0.        ]])

In [42]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten

In [43]:
model = Sequential()

In [61]:
model.add(Dense(7,activation='relu',input_dim=7))
model.add(Dense(7,activation='relu'))
model.add(Dense(1,activation='linear'))

In [62]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 7)                 56

 dense_1 (Dense)             (None, 1)                 8

 dense_2 (Dense)             (None, 7)                 14

 dense_3 (Dense)             (None, 7)                 56

 dense_4 (Dense)             (None, 1)                 8

=================================================================
Total params: 142
Trainable params: 142
Non-trainable params: 0
_________________________________________________________________

In [63]:
model.compile(loss='mean_squared_error',optimizer='Adam')

In [72]:
history = model.fit(X_train_trf,Y_train,epochs=200,validation_split=0.2)

Epoch 1/200
7/7 [==============================] - 0s 21ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 2/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 3/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 4/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 5/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0030
Epoch 6/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 7/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 8/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0031
Epoch 9/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0045 - val_loss: 0.0028
Epoch 10/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 11/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0030
Epoch 12/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 13/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 14/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0031
Epoch 15/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 16/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 17/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 18/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0045 - val_loss: 0.0029
Epoch 19/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 20/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 21/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0030
Epoch 22/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 23/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 24/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0030
Epoch 25/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 26/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0045 - val_loss: 0.0027
Epoch 27/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0031
Epoch 28/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0045 - val_loss: 0.0027
Epoch 29/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0030
Epoch 30/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 31/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 32/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0030
Epoch 33/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 34/200
7/7 [==============================] - 0s 15ms/step - loss: 0.0046 - val_loss: 0.0030
Epoch 35/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0026
Epoch 36/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0030
Epoch 37/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 38/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 39/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 40/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 41/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0026
Epoch 42/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 43/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 44/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 45/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 46/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 47/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 48/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0031
Epoch 49/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 50/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 51/200
7/7 [==============================] - 0s 14ms/step - loss: 0.0044 - val_loss: 0.0030
Epoch 52/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0026
Epoch 53/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 54/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0030
Epoch 55/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 56/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0046 - val_loss: 0.0026
Epoch 57/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0044 - val_loss: 0.0032
Epoch 58/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 59/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0045 - val_loss: 0.0027
Epoch 60/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 61/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 62/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 63/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 64/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 65/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 66/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 67/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 68/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0044 - val_loss: 0.0026
Epoch 69/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 70/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 71/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 72/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 73/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 74/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 75/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0045 - val_loss: 0.0026
Epoch 76/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0031
Epoch 77/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 78/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 79/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 80/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 81/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 82/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 83/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0029

Epoch 84/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 85/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0044 - val_loss: 0.0026
Epoch 86/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0043 - val_loss: 0.0030
Epoch 87/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 88/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0044 - val_loss: 0.0026
Epoch 89/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0043 - val_loss: 0.0030
Epoch 90/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 91/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0045 - val_loss: 0.0026
Epoch 92/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0046 - val_loss: 0.0029
Epoch 93/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0026
Epoch 94/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 95/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 96/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 97/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 98/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 99/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0043 - val_loss: 0.0028
Epoch 100/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 101/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 102/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 103/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 104/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 105/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 106/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 107/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 108/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 109/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 110/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 111/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 112/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0025
Epoch 113/200
7/7 [==============================] - 0s 14ms/step - loss: 0.0043 - val_loss: 0.0028
Epoch 114/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 115/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0026
Epoch 116/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0029
Epoch 117/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 118/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0026
Epoch 119/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 120/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 121/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0029
Epoch 122/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0026
Epoch 123/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0025
Epoch 124/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0029
Epoch 125/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 126/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0025
Epoch 127/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0028
Epoch 128/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 129/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0025
Epoch 130/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0028
Epoch 131/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 132/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 133/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 134/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 135/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 136/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0043 - val_loss: 0.0028
Epoch 137/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 138/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 139/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0028
Epoch 140/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 141/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 142/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 143/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0044 - val_loss: 0.0026
Epoch 144/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 145/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0028
Epoch 146/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 147/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 148/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0029
Epoch 149/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0025
Epoch 150/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 151/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 152/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 153/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 154/200
7/7 [==============================] - 0s 14ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 155/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 156/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 157/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 158/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0028
Epoch 159/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 160/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 161/200
7/7 [==============================] - 0s 8ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 162/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 163/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 164/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 165/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 166/200

7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0028
Epoch 167/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 168/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 169/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 170/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 171/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 172/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 173/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 174/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 175/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 176/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 177/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 178/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 179/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 180/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 181/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0044 - val_loss: 0.0027
Epoch 182/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0023
Epoch 183/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0030
Epoch 184/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 185/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0025
Epoch 186/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0028
Epoch 187/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 188/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0043 - val_loss: 0.0025
Epoch 189/200
7/7 [==============================] - 0s 14ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 190/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 191/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 192/200
7/7 [==============================] - 0s 13ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 193/200
7/7 [==============================] - 0s 12ms/step - loss: 0.0044 - val_loss: 0.0025
Epoch 194/200
7/7 [==============================] - 0s 9ms/step - loss: 0.0043 - val_loss: 0.0028
Epoch 195/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0043 - val_loss: 0.0024
Epoch 196/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 197/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0043 - val_loss: 0.0026
Epoch 198/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0043 - val_loss: 0.0027
Epoch 199/200
7/7 [==============================] - 0s 11ms/step - loss: 0.0044 - val_loss: 0.0025
Epoch 200/200
7/7 [==============================] - 0s 10ms/step - loss: 0.0044 - val_loss: 0.0028

In [73]:
y_pred = model.predict(X_test_trf)

5/5 [==============================] - 0s 2ms/step

In [74]:
from sklearn.metrics import r2_score

In [75]:
r2_score(Y_test,y_pred)

0.7990925128221698